# Site settings
title: Karinna Iniguez
header-img: img/home-bg.png
email: karinnainiguez@gmail.com
copyright_name: karinnainiguez
description: > # this means to ignore newlines until "baseurl:"
  Hello Coding World :)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  karinnainiguez
learn_profile: karinnainiguez
email_username: karinnainiguez@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
